# Generated by Django 4.2.3 on 2023-07-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='rent_per_hour',
            new_name='rent_price_per_hour',
        ),
        migrations.RemoveField(
            model_name='room',
            name='booking_details',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodge.room')),
            ],
        ),
    ]
